---
title: "Quiz_3_In_Class"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Quiz 3 In-Class
Complete this quiz in a .Rmd file. To turn in the quiz, push both a .Rmd file and a knitted .html file to your GitHub site.

Statement of Integrity: Copy and paste the following statement and then sign your name (by typing it) on the line below.

“All work presented is my own. I have not communicated with or worked with anyone else on this quiz.”

Lily Kasperek

Collaboration Reminder: You may not communicate with or work with anyone else on this quiz, but you may use any of our course materials or materials on the Internet.

__Question 1__ (5 points). Suppose you do the following:

You go to your GitHub site and make a change to the README file (adding a sentence, for example).
In R Studio, you update one of your .Rmd files, adding a line of code and commit the file.
You attempt to push the new file to your GitHub site.
Once you get to the third step, you’ll get an error when you try to push. Why? What do you need to do first before you make the push in Step 3?

The error is because the branch will be ahead by one. You should first pull your updated readme file to RStudio, by committing the change on GitHub and then pressing the pull button on RStudio. Then you should save the updated .Rmd file to RStudio before you attempt to push it to GitHub. 

__Question 2__ (6 points). Give 2 advantages of using Git and GitHub. These must be advantages that we discussed in class (so you should not simply google “advantages of Git” and give the first two things that pop up).

One advantage of Git is version control. This means that when working on a project, you can use git and github to go back to an older version of that project. Another advantage is collaboration. When you make a repository public, this makes it much easier for communication and collaboration, as opposed to emailing code back and forth when running into difficulty.

__Question 3__ (6 points). Choose 1 of the 12 principles of the ethical practice of data science that you think is the most difficult to execute. Give a short, possibly hypothetical, example that illustrates how that principle could be difficult to follow.

One of the 12 principles of ethical data science that I think is the most difficult to execute is, "Recognize and mitigate bias in ourselves and in the data we use." Although this principle is probably one of the most important, I do believe it is hard to pull off. The Challenger example demonstrates this. Biases are subconscious, and thus, it is very difficult to actively be aware of those biases. However, I think it can be hard to recognize bias in less dire situations as well. For example, when doing a report on something like average world happiness, we may have a selection bias of picking Western countries without even realizing it, resulting in a project that only analyzes the data on certain countries in a certain part of the world rather than many countries throughout many regions of the world. 

__Question 4__ (6 points). The authors of Data Feminism argued that data scientists should “embrace emotion,” not ignore it when building visuals. State the example that the authors used to show how emotion can be used to make a visual stronger. Then, give an argument against “embracing emotion.” In other words, give an argument that data visualizations should be devoid of emotion as much as possible, even if that’s not what you believe.

The authors of Data Feminism use the Periscopic visualization of gun deaths in the United States, that also provides how many lives were stolen from victims, as well as their names, ages, and circumstances of their deaths among other things. One argument against using emotion for data visualization is that it does not allow for viewers to interpret the data for themselves. Those who argue in defense of neutral data, believes that emotion can bring an element of persuasion, preventing viewers from forming their own interpretation or opinion of the data. Many others believe that emotional data is less objective, and thus less "true" as well. 

__Question 5__ (2 points). These two points are given for committing your .Rmd and .html files with a commit message correctly, and pushing them to your GitHub site.